// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using st10083262_cldv6211_poe_part_3.Data;

#nullable disable

namespace st10083262_cldv6211_poe_part_3.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20230627192841_1")]
    partial class _1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("st10083262_cldv6211_poe_part_3.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CarID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"));

                    b.Property<int?>("BodyTypeId")
                        .HasColumnType("int")
                        .HasColumnName("BodyTypeID");

                    b.Property<bool?>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int?>("MakeId")
                        .HasColumnType("int")
                        .HasColumnName("MakeID");

                    b.Property<string>("Model")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("CarId");

                    b.HasIndex("BodyTypeId");

                    b.HasIndex("MakeId");

                    b.HasIndex("RegistrationNumber");

                    b.ToTable("Car");
                });

            modelBuilder.Entity("st10083262_cldv6211_poe_part_3.Models.CarBodyType", b =>
                {
                    b.Property<int>("BodyTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BodyTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BodyTypeId"));

                    b.Property<string>("TypeName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BodyTypeId");

                    b.ToTable("CarBodyType");
                });

            modelBuilder.Entity("st10083262_cldv6211_poe_part_3.Models.CarMake", b =>
                {
                    b.Property<int>("MakeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MakeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MakeId"));

                    b.Property<string>("ManufacturerName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MakeId");

                    b.ToTable("CarMake");
                });

            modelBuilder.Entity("st10083262_cldv6211_poe_part_3.Models.CarRental", b =>
                {
                    b.Property<int>("RentalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RentalID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentalId"));

                    b.Property<int?>("DriverId")
                        .HasColumnType("int")
                        .HasColumnName("DriverID");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("InspectorId")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("InspectorID");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<decimal?>("RentalPrice")
                        .HasColumnType("money");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("RentalId");

                    b.HasIndex("DriverId");

                    b.HasIndex("InspectorId");

                    b.HasIndex("RegistrationNumber");

                    b.ToTable("CarRental");
                });

            modelBuilder.Entity("st10083262_cldv6211_poe_part_3.Models.CarReturn", b =>
                {
                    b.Property<int>("ReturnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReturnID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReturnId"));

                    b.Property<int?>("ElapsedDays")
                        .HasColumnType("int");

                    b.Property<decimal?>("FineAmount")
                        .HasColumnType("money");

                    b.Property<int?>("RentalId")
                        .HasColumnType("int")
                        .HasColumnName("RentalID");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("date");

                    b.HasKey("ReturnId");

                    b.HasIndex("RentalId");

                    b.ToTable("CarReturn");
                });

            modelBuilder.Entity("st10083262_cldv6211_poe_part_3.Models.CarService", b =>
                {
                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int?>("Kilometerstravelled")
                        .HasColumnType("int")
                        .HasColumnName("KMTravelled");

                    b.Property<int?>("ServicedKilometers")
                        .HasColumnType("int")
                        .HasColumnName("ServicedKM");

                    b.HasKey("RegistrationNumber");

                    b.ToTable("CarService");
                });

            modelBuilder.Entity("st10083262_cldv6211_poe_part_3.Models.Detail", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DetailID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("DetailId");

                    b.ToTable("Detail");
                });

            modelBuilder.Entity("st10083262_cldv6211_poe_part_3.Models.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DriverID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverId"));

                    b.Property<int?>("DetailId")
                        .HasColumnType("int")
                        .HasColumnName("DetailID");

                    b.Property<string>("ResidenceAddress")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("DriverId");

                    b.HasIndex(new[] { "DetailId" }, "UQ_Drivers_1")
                        .IsUnique()
                        .HasFilter("[DetailID] IS NOT NULL");

                    b.ToTable("Driver");
                });

            modelBuilder.Entity("st10083262_cldv6211_poe_part_3.Models.Inspector", b =>
                {
                    b.Property<string>("InspectorId")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("InspectorID");

                    b.Property<int?>("DetailId")
                        .HasColumnType("int")
                        .HasColumnName("DetailID");

                    b.HasKey("InspectorId");

                    b.HasIndex(new[] { "DetailId" }, "UQ_Inspector_1")
                        .IsUnique()
                        .HasFilter("[DetailID] IS NOT NULL");

                    b.ToTable("Inspector");
                });

            modelBuilder.Entity("st10083262_cldv6211_poe_part_3.Models.Car", b =>
                {
                    b.HasOne("st10083262_cldv6211_poe_part_3.Models.CarBodyType", "BodyType")
                        .WithMany("Cars")
                        .HasForeignKey("BodyTypeId");

                    b.HasOne("st10083262_cldv6211_poe_part_3.Models.CarMake", "Make")
                        .WithMany("Cars")
                        .HasForeignKey("MakeId");

                    b.HasOne("st10083262_cldv6211_poe_part_3.Models.CarService", "RegisteredCar")
                        .WithMany("Cars")
                        .HasForeignKey("RegistrationNumber");

                    b.Navigation("BodyType");

                    b.Navigation("Make");

                    b.Navigation("RegisteredCar");
                });

            modelBuilder.Entity("st10083262_cldv6211_poe_part_3.Models.CarRental", b =>
                {
                    b.HasOne("st10083262_cldv6211_poe_part_3.Models.Driver", "Driver")
                        .WithMany("CarRentals")
                        .HasForeignKey("DriverId");

                    b.HasOne("st10083262_cldv6211_poe_part_3.Models.Inspector", "Inspector")
                        .WithMany("CarRentals")
                        .HasForeignKey("InspectorId");

                    b.HasOne("st10083262_cldv6211_poe_part_3.Models.CarService", "CarNoNavigation")
                        .WithMany("CarRentals")
                        .HasForeignKey("RegistrationNumber");

                    b.Navigation("CarNoNavigation");

                    b.Navigation("Driver");

                    b.Navigation("Inspector");
                });

            modelBuilder.Entity("st10083262_cldv6211_poe_part_3.Models.CarReturn", b =>
                {
                    b.HasOne("st10083262_cldv6211_poe_part_3.Models.CarRental", "RentalInfo")
                        .WithMany("CarReturns")
                        .HasForeignKey("RentalId");

                    b.Navigation("RentalInfo");
                });

            modelBuilder.Entity("st10083262_cldv6211_poe_part_3.Models.Driver", b =>
                {
                    b.HasOne("st10083262_cldv6211_poe_part_3.Models.Detail", "PersonalDetails")
                        .WithOne("Driver")
                        .HasForeignKey("st10083262_cldv6211_poe_part_3.Models.Driver", "DetailId");

                    b.Navigation("PersonalDetails");
                });

            modelBuilder.Entity("st10083262_cldv6211_poe_part_3.Models.Inspector", b =>
                {
                    b.HasOne("st10083262_cldv6211_poe_part_3.Models.Detail", "PersonalDetails")
                        .WithOne("Inspector")
                        .HasForeignKey("st10083262_cldv6211_poe_part_3.Models.Inspector", "DetailId");

                    b.Navigation("PersonalDetails");
                });

            modelBuilder.Entity("st10083262_cldv6211_poe_part_3.Models.CarBodyType", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("st10083262_cldv6211_poe_part_3.Models.CarMake", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("st10083262_cldv6211_poe_part_3.Models.CarRental", b =>
                {
                    b.Navigation("CarReturns");
                });

            modelBuilder.Entity("st10083262_cldv6211_poe_part_3.Models.CarService", b =>
                {
                    b.Navigation("CarRentals");

                    b.Navigation("Cars");
                });

            modelBuilder.Entity("st10083262_cldv6211_poe_part_3.Models.Detail", b =>
                {
                    b.Navigation("Driver");

                    b.Navigation("Inspector");
                });

            modelBuilder.Entity("st10083262_cldv6211_poe_part_3.Models.Driver", b =>
                {
                    b.Navigation("CarRentals");
                });

            modelBuilder.Entity("st10083262_cldv6211_poe_part_3.Models.Inspector", b =>
                {
                    b.Navigation("CarRentals");
                });
#pragma warning restore 612, 618
        }
    }
}
